# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"u\n\x0fLocationMessage\x12\x13\n\x0blocation_id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\")\n\x12LocationGetMessage\x12\x13\n\x0blocation_id\x18\x01 \x01(\x05\"[\n LocationGetFilteredByDateMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"\x91\x01\n!LocationGetFilteredByRangeMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x0e\n\x06meters\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\":\n\x13LocationMessageList\x12#\n\tlocations\x18\x01 \x03(\x0b\x32\x10.LocationMessage2\x8b\x02\n\x0fLocationService\x12,\n\x06\x43reate\x12\x10.LocationMessage\x1a\x10.LocationMessage\x12,\n\x03Get\x12\x13.LocationGetMessage\x1a\x10.LocationMessage\x12L\n\x11GetFilteredByDate\x12!.LocationGetFilteredByDateMessage\x1a\x14.LocationMessageList\x12N\n\x12GetLocationsWithin\x12\".LocationGetFilteredByRangeMessage\x1a\x14.LocationMessageListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONMESSAGE']._serialized_start=18
  _globals['_LOCATIONMESSAGE']._serialized_end=135
  _globals['_LOCATIONGETMESSAGE']._serialized_start=137
  _globals['_LOCATIONGETMESSAGE']._serialized_end=178
  _globals['_LOCATIONGETFILTEREDBYDATEMESSAGE']._serialized_start=180
  _globals['_LOCATIONGETFILTEREDBYDATEMESSAGE']._serialized_end=271
  _globals['_LOCATIONGETFILTEREDBYRANGEMESSAGE']._serialized_start=274
  _globals['_LOCATIONGETFILTEREDBYRANGEMESSAGE']._serialized_end=419
  _globals['_LOCATIONMESSAGELIST']._serialized_start=421
  _globals['_LOCATIONMESSAGELIST']._serialized_end=479
  _globals['_LOCATIONSERVICE']._serialized_start=482
  _globals['_LOCATIONSERVICE']._serialized_end=749
# @@protoc_insertion_point(module_scope)
