apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location-app
  ports:
  - protocol: TCP
    port: 5006
    targetPort: 5006
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: location-nodeport
spec:
  selector:
    app: location-app  
  ports:
  - name: "np-5006"
    port: 5006
    targetPort: 5006
    nodePort: 30006
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-configmap
data:
  GRPC_PORT: "5006"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-app
  name: location-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-app
  template:
    metadata:
      labels:
        app: location-app
    spec:
      containers:
      - image: aplacidi/udac-location-grpc-service:latest
        name: udac-location-grpc-service
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: location-configmap
              key: GRPC_PORT
      restartPolicy: Always