apiVersion: v1
kind: Service
metadata:
  name: person-service
spec:
  selector:
    app: person-app
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: person-nodeport
spec:
  selector:
    app: person-app  
  ports:
  - name: "np-5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: person-configmap
data:
  GRPC_PORT: "5005"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-app
  name: person-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-app
  template:
    metadata:
      labels:
        app: person-app
    spec:
      containers:
      - image: aplacidi/udac-person-grpc-service:latest
        name: udac-person-grpc-service
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: person-configmap
              key: GRPC_PORT
      restartPolicy: Always