apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-1
  ports:
    - protocol: TCP
      name: "9090"
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: "9091"
      port: 9091
      targetPort: 9091
    - protocol: TCP
      name: "9092"
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-2
  ports:
    - protocol: TCP
      name: "9090"
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: "9091"
      port: 9091
      targetPort: 9091
    - protocol: TCP
      name: "9094"
      port: 9094
      targetPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-3
  ports:
    - protocol: TCP
      name: "9090"
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: "9091"
      port: 9091
      targetPort: 9091
    - protocol: TCP
      name: "9096"
      port: 9096
      targetPort: 9096
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - name: "np-9098"
      protocol: TCP
      port: 9098
      targetPort: 8080
      nodePort: 30098