name: UdaConnect - Package with Docker
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - Person service
        uses: docker/build-push-action@v2
        with:
          context: ./modules/person-grpc-service
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-person-grpc-service:latest
      -
        name: Build and push - Location Service
        uses: docker/build-push-action@v2
        with:
          context: ./modules/location-grpc-service
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-location-grpc-service:latest
      -
        name: Build and push - Kafka consumer
        uses: docker/build-push-action@v2
        with:
          context: ./modules/kafka-location-consumer
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-kafka-location-consumer:latest
      -
        name: Build and push - Flask Web service
        uses: docker/build-push-action@v2
        with:
          context: ./modules/udaconnect-rest-service
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-rest-service:latest
      -
        name: Build and push - UdaConnect Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-frontend:latest